mongodb:
  dbName: "test_db"
  host: "host.docker.internal"
micronaut:
  application:
    name: test_project
    server:
      port: 8080
  server:
    url: "http://localhost:8080"
    port: 8080
    host: "0.0.0.0"
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
      swagger:
        paths: "classpath:META-INF/swagger"
        mapping: "/swagger/**"
      swagger-ui:
        paths: "classpath:META-INF/swagger/views/swagger-ui"
        mapping: "/swagger-ui/**"
  mongodb:
    uri: "mongodb://localhost:27017"
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

endpoints:
  all:
    sensitive: false
    path: "/system"
  beans:
    enabled: true
    sensitive: false
    build:
      enabled: true
  env:
    enabled: true
    sensitive: false


