micronaut:
  application:
    name: test_project
    ports:
      - '8080:8080'
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  mongodb:
    uri: "mongodb://mongodb:27017"
